import {
  type CheckoutItemsType,
  type CheckoutThemeType,
} from "@checkout-layout/types/checkout";

export const initialLayoutData: CheckoutItemsType = {
  id: "1",
  name: "Produto Plus Ultra",
  type: "PHYSICAL",
  paymentFormat: "ONE_TIME",
  description:
    "Produto Plus Ultra de alta qualidade com 100% de couro animal e 100% de tudo que você precisa.",
  image: "/not-product.png",
  urlRedirect: "https://google.com",
  urlBack: "https://google.com",
  offer: {
    id: "1",
    name: "Checkout",
    description: "Checkout",
    slug: "checkout",
    priceFake: 120,
    price: 100,
  },
  shippingOptions: [
    {
      id: "shipping-1",
      name: "Frete Grátis",
      description: "18 a 30 dias",
      price: 0,
      image: "",
    },
    {
      id: "shipping-2",
      name: "PAC",
      description: "7 a 10 dias",
      price: 19.71,
      image: "",
    },
    {
      id: "shipping-3",
      name: "Sedex (Mais escolhido)",
      description: "5 a 6 dias",
      price: 24.97,
      image: "",
    },
  ],
  orderBumps: [
    {
      id: "bump-1",
      name: "Checkout Oferta 1",
      description: "Checkout Oferta 1",
      image: "/not-product.png",
      callToAction: "Checkout",
      price: 100,
      priceFake: 120,
    },
    {
      id: "bump-2",
      name: "Checkout Oferta 2",
      description: "Checkout Oferta 2",
      image: "/not-product.png",
      callToAction: "Checkout",
      price: 100,
      priceFake: 120,
    },
  ],
};

export const initialLayoutTheme: CheckoutThemeType = {
  theme: "SIMPLE",
  steps: "three",
  font: "Poppins",
  radius: "square",
  cartVisible: true,
  socialProofs: [],
  defaultImages: {
    favicon:
      "https://res.cloudinary.com/doccennng/image/upload/v1765583881/icone_tyevxz.png",
    logo: "https://res.cloudinary.com/doccennng/image/upload/v1765583881/icone_tyevxz.png",
    logoPosition: "left",
    bannerDesktop:
      "https://res.cloudinary.com/doccennng/image/upload/v1765655664/banner-desktop_ppicea.png",
    bannerMobile:
      "https://res.cloudinary.com/doccennng/image/upload/v1765655661/banner-mobile_przbaj.png",
  },
  defaultTexts: {
    titlePageText: "Checkout de pagamento",
    buttonText: "Fazer pedido",
    idText: "Checkout",
    copyRightText: "© 2025 Loja Profissional",
    noticeBarText: "Frete grátis apenas hoje!",
    shopNameText: "Loja",
    productTitleText: "Produto Título",
    emailText: "exemple@gmail.com",
    addressText: "Rua Exemplo, 123",
    whatsappText: "(11) 99999-9999",
    termsText: "Termos de uso",
    privacyPolicyText: "Política de privacidade",
    exchangePolicyText: "Política de trocas e devoluções",
  },
  defaultSnippets: {
    isLogo: true,
    isMenuFixedTop: true,
    isNoticeBar: true,
    isBanner: false,
    isSocialProof: true,
    isPayment: true,
    isSecurity: true,
    isCopyRight: true,
    isCountdown: true,
    isTerms: true,
    isPrivacyPolicy: true,
    isExchangePolicy: true,
    isWhatsApp: true,
    isEmail: true,
    isAddress: true,
    isCNPJ: true,
    isCardShadow: false,
    isButtonShadow: true,
    isButtonPulse: true,
    isFinishButtonShadow: true,
    isFinishButtonPulse: true,
    isCartDiscount: true,
    isSealSecurity: true,
    isCountProduct: true,
    isCountBump: true,
  },
  defaultColors: {
    headerBackground: "#ffffff",
    cardBackground: "#ffffff",
    cardText: "#313c52",
    cardDescription: "#909090",
    cardPriceTotal: "#c084fc",
    textDiscount: "#c084fc",
    primary: "#c084fc",
    secondary: "#16a34a",
    background: "#F3F3F3",
    surface: "#ffffff",
    noticeBar: "#c084fc",
    buttonColor: "#c084fc",
    buttonTextColor: "#ffffff",
    finishButtonColor: "#35c06f",
    finishButtonTextColor: "#ffffff",
    socialProofStars: "#ffd500",
    stepCircle: "#283368",
    stepText: "#ffffff",
    footerText: "#313c52",
    footerBackground: "#fafafa",
    orderBumpText: "#313c52",
    orderBumpBackground: "#cff2dd",
    orderBumpBorder: "#1e9442",
    orderBumpButton: "#c084fc",
    orderBumpButtonText: "#ffffff",
    orderBumpPrice: "#35c06f",
    sealSecurityColor: "#008000",
  },
  defaultMargins: {
    marginNoticeBar: "2",
  },
  defaultSizes: {
    sizeNoticeBar: "base",
  },
};

export function adaptCheckoutTheme(data: any): CheckoutThemeType {
  return {
    theme: data?.theme || "SIMPLE",
    steps: data?.steps || "three",
    font: data?.font || "Inter",
    radius: data?.radius || "square",
    cartVisible: data?.cartVisible ?? true,
    socialProofs: data?.socialProofs || initialLayoutTheme.socialProofs,
    defaultImages: {
      favicon:
        data?.defaultImages?.favicon ||
        initialLayoutTheme.defaultImages.favicon,
      logo: data?.defaultImages?.logo || initialLayoutTheme.defaultImages.logo,
      logoPosition: data?.defaultImages?.logoPosition || "left",
      bannerDesktop:
        data?.defaultImages?.bannerDesktop ||
        initialLayoutTheme.defaultImages.bannerDesktop,
      bannerMobile:
        data?.defaultImages?.bannerMobile ||
        initialLayoutTheme.defaultImages.bannerMobile,
    },
    defaultTexts: {
      titlePageText:
        data?.defaultTexts?.titlePageText || "Checkout de pagamento",
      buttonText: data?.defaultTexts?.buttonText || "Fazer pedido",
      idText: data?.defaultTexts?.idText || "21.999.999/9923131",
      copyRightText:
        data?.defaultTexts?.copyRightText || "© 2025 Loja Profissional",
      noticeBarText:
        data?.defaultTexts?.noticeBarText || "Frete grátis apenas hoje!",
      shopNameText: data?.defaultTexts?.shopNameText || "Loja",
      productTitleText:
        data?.defaultTexts?.productTitleText || "Produto Título",
      emailText: data?.defaultTexts?.emailText || "exemple@gmail.com",
      addressText: data?.defaultTexts?.addressText || "Rua Exemplo, 123",
      whatsappText: data?.defaultTexts?.whatsappText || "(11) 99999-9999",
      termsText: data?.defaultTexts?.termsText || "Termos de uso",
      privacyPolicyText:
        data?.defaultTexts?.privacyPolicyText || "Política de privacidade",
      exchangePolicyText:
        data?.defaultTexts?.exchangePolicyText || "Política de trocas",
    },
    defaultSnippets: {
      isLogo: data?.defaultSnippets?.isLogo ?? true,
      isMenuFixedTop: data?.defaultSnippets?.isMenuFixedTop ?? true,
      isNoticeBar: data?.defaultSnippets?.isNoticeBar ?? true,
      isBanner: data?.defaultSnippets?.isBanner ?? false,
      isSocialProof: data?.defaultSnippets?.isSocialProof ?? true,
      isPayment: data?.defaultSnippets?.isPayment ?? true,
      isSecurity: data?.defaultSnippets?.isSecurity ?? true,
      isCopyRight: data?.defaultSnippets?.isCopyRight ?? true,
      isCountdown: data?.defaultSnippets?.isCountdown ?? true,
      isTerms: data?.defaultSnippets?.isTerms ?? true,
      isPrivacyPolicy: data?.defaultSnippets?.isPrivacyPolicy ?? true,
      isExchangePolicy: data?.defaultSnippets?.isExchangePolicy ?? true,
      isWhatsApp: data?.defaultSnippets?.isWhatsApp ?? true,
      isEmail: data?.defaultSnippets?.isEmail ?? true,
      isAddress: data?.defaultSnippets?.isAddress ?? true,
      isCNPJ: data?.defaultSnippets?.isCNPJ ?? true,
      isCardShadow: data?.defaultSnippets?.isCardShadow ?? false,
      isButtonShadow: data?.defaultSnippets?.isButtonShadow ?? true,
      isButtonPulse: data?.defaultSnippets?.isButtonPulse ?? true,
      isFinishButtonShadow: data?.defaultSnippets?.isFinishButtonShadow ?? true,
      isFinishButtonPulse: data?.defaultSnippets?.isFinishButtonPulse ?? true,
      isCartDiscount: data?.defaultSnippets?.isCartDiscount ?? true,
      isSealSecurity: data?.defaultSnippets?.isSealSecurity ?? true,
      isCountProduct: data?.defaultSnippets?.isCountProduct ?? true,
      isCountBump: data?.defaultSnippets?.isCountBump ?? true,
    },
    defaultColors: {
      headerBackground: data?.defaultColors?.headerBackground || "#ffffff",
      cardBackground: data?.defaultColors?.cardBackground || "#ffffff",
      cardText: data?.defaultColors?.cardText || "#313c52",
      cardDescription: data?.defaultColors?.cardDescription || "#909090",
      cardPriceTotal: data?.defaultColors?.cardPriceTotal || "#c084fc",
      textDiscount: data?.defaultColors?.textDiscount || "#c084fc",
      primary: data?.defaultColors?.primary || "#c084fc",
      secondary: data?.defaultColors?.secondary || "#16a34a",
      background: data?.defaultColors?.background || "#F3F3F3",
      surface: data?.defaultColors?.surface || "#ffffff",
      noticeBar: data?.defaultColors?.noticeBar || "#c084fc",
      buttonColor: data?.defaultColors?.buttonColor || "#c084fc",
      buttonTextColor: data?.defaultColors?.buttonTextColor || "#ffffff",
      finishButtonColor: data?.defaultColors?.finishButtonColor || "#35c06f",
      finishButtonTextColor:
        data?.defaultColors?.finishButtonTextColor || "#ffffff",
      socialProofStars: data?.defaultColors?.socialProofStars || "#ffd500",
      stepCircle: data?.defaultColors?.stepCircle || "#283368",
      stepText: data?.defaultColors?.stepText || "#ffffff",
      footerText: data?.defaultColors?.footerText || "#313c52",
      footerBackground: data?.defaultColors?.footerBackground || "#fafafa",
      orderBumpText: data?.defaultColors?.orderBumpText || "#313c52",
      orderBumpBackground:
        data?.defaultColors?.orderBumpBackground || "#cff2dd",
      orderBumpBorder: data?.defaultColors?.orderBumpBorder || "#1e9442",
      orderBumpButton: data?.defaultColors?.orderBumpButton || "#c084fc",
      orderBumpButtonText:
        data?.defaultColors?.orderBumpButtonText || "#ffffff",
      orderBumpPrice: data?.defaultColors?.orderBumpPrice || "#35c06f",
      sealSecurityColor: data?.defaultColors?.sealSecurityColor || "#008000",
    },
    defaultMargins: {
      marginNoticeBar: data?.defaultMargins?.marginNoticeBar || "2",
    },
    defaultSizes: {
      sizeNoticeBar: data?.defaultSizes?.sizeNoticeBar || "base",
    },
  };
}
